import rp from "request-promise-native"
import request from "sync-request"
import environment from "node-env-file"

export default class PopulationProvider {
    constructor() {
        let env = environment(".env")
        this.base_url = env.POPULATIONURL
        this.countries = [
            "Afghanistan",
            "Albania",
            "Algeria",
            "Angola",
            "Antigua and Barbuda",
            "Arab Rep of Egypt",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "The Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei Darussalam",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cote-d-Ivoire",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Caribbean",
            "Central African Republic",
            "Central Asia",
            "Chad",
            "Channel Islands",
            "Chile",
            "China",
            "Hong Kong SAR-China",
            "Macao SAR China",
            "Colombia",
            "Comoros",
            "Congo",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Curacao",
            "Cyprus",
            "Czech Republic",
            "Dem Peoples Rep of Korea",
            "Dem Rep of Congo",
            "Denmark",
            "Djibouti",
            "Dominican Republic",
            "Ecuador",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Federated States of Micronesia",
            "Fiji",
            "Finland",
            "France",
            "French Guiana",
            "French Polynesia",
            "FYR Macedonia",
            "Gabon",
            "The Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Islamic Republic of Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kuwait",
            "Kyrgyz Republic",
            "Lao PDR",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Lithuania",
            "Luxembourg",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Melanesia",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nepal",
            "The Netherlands",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Norway",
            "Oman",
            "Pakistan",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Polynesia",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Reunion",
            "RB-de-Venezuela",
            "Rep of Korea",
            "Rep of Yemen",
            "Romania",
            "Russian Federation",
            "Rwanda",
            "St-Lucia",
            "St-Vincent and the Grenadines",
            "Samoa",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovak Republic",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South America",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "West Bank and Gaza",
            "Sub-Saharan Africa",
            "Sudan",
            "Suriname",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syrian Arab Rep",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "US Virgin Islands",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vietnam",
            "Western Sahara",
            "Zambia",
            "Zimbabwe"
        ]
        this.populations = {
            "Afghanistan": 34169169,
            "Albania": 2911428,
            "Algeria": 41063753,
            "Angola": 26655513,
            "Antigua and Barbuda": 93659,
            "Arab Rep of Egypt": 95215102,
            "Argentina": 44272125,
            "Armenia": 3031670,
            "Aruba": 104588,
            "Australia": 24641662,
            "Austria": 8592400,
            "Azerbaijan": 9973697,
            "The Bahamas": 397164,
            "Bahrain": 1418895,
            "Bangladesh": 164827718,
            "Barbados": 285744,
            "Belarus": 9458535,
            "Belgium": 11443830,
            "Belize": 374651,
            "Benin": 11458611,
            "Bhutan": 792877,
            "Bolivia": 11052864,
            "Bosnia and Herzegovina": 3792759,
            "Botswana": 2343981,
            "Brazil": 211243220,
            "Brunei Darussalam": 434448,
            "Bulgaria": 7045259,
            "Burkina Faso": 19173322,
            "Burundi": 11936481,
            "Cote-d-Ivoire": 23815886,
            "Cabo Verde": 533468,
            "Cambodia": 16076370,
            "Cameroon": 24513689,
            "Canada": 36626083,
            "Caribbean": 43767545,
            "Central African Republic": 5098826,
            "Central Asia": 69241030,
            "Chad": 14965482,
            "Channel Islands": 165235,
            "Chile": 18313495,
            "China": 1388232672,
            "Hong Kong SAR-China": 7401941,
            "Macao SAR China": 606384,
            "Colombia": 49067981,
            "Comoros": 825920,
            "Congo": 4866243,
            "Costa Rica": 4905626,
            "Croatia": 4209815,
            "Cuba": 11390184,
            "Curacao": 159987,
            "Cyprus": 1187575,
            "Czech Republic": 10555130,
            "Dem Peoples Rep of Korea": 25405296,
            "Dem Rep of Congo": 82242685,
            "Denmark": 5711837,
            "Djibouti": 911382,
            "Dominican Republic": 10766564,
            "Ecuador": 16625776,
            "El Salvador": 6167147,
            "Equatorial Guinea": 894464,
            "Eritrea": 5481906,
            "Estonia": 1305755,
            "Ethiopia": 104344901,
            "Federated States of Micronesia": 105566,
            "Fiji": 902547,
            "Finland": 5541274,
            "France": 64938716,
            "French Guiana": 282761,
            "French Polynesia": 288685,
            "FYR Macedonia": 2083385,
            "Gabon": 1801232,
            "The Gambia": 2120418,
            "Georgia": 3972532,
            "Germany": 80636124,
            "Ghana": 28656723,
            "Greece": 10892931,
            "Grenada": 107850,
            "Guadeloupe": 472462,
            "Guam": 174214,
            "Guatemala": 17005497,
            "Guinea": 13290659,
            "Guinea-Bissau": 1932871,
            "Guyana": 774407,
            "Haiti": 10983274,
            "Honduras": 8304677,
            "Hungary": 9787905,
            "Iceland": 334303,
            "India": 1342512742,
            "Indonesia": 263510146,
            "Islamic Republic of Iran": 80945718,
            "Iraq": 38654287,
            "Ireland": 4749153,
            "Israel": 8323248,
            "Italy": 59797978,
            "Jamaica": 2813285,
            "Japan": 126045211,
            "Jordan": 7876703,
            "Kazakhstan": 18064470,
            "Kenya": 48466928,
            "Kiribati": 116405,
            "Kuwait": 4099932,
            "Kyrgyz Republic": 6124945,
            "Lao PDR": 7037521,
            "Latvia": 1944565,
            "Lebanon": 6039277,
            "Lesotho": 2185159,
            "Liberia": 4730437,
            "Libya": 6408742,
            "Lithuania": 2830582,
            "Luxembourg": 584103,
            "Madagascar": 25612972,
            "Malawi": 18298679,
            "Malaysia": 31164177,
            "Maldives": 375867,
            "Mali": 18689966,
            "Malta": 420521,
            "Martinique": 396071,
            "Mauritania": 4266448,
            "Mauritius": 1281353,
            "Mayotte": 253068,
            "Melanesia": 9988670,
            "Mexico": 130222815,
            "Micronesia": 536911,
            "Moldova": 4055017,
            "Mongolia": 3051900,
            "Montenegro": 626250,
            "Morocco": 35241418,
            "Mozambique": 29537914,
            "Myanmar": 54836483,
            "Namibia": 2568569,
            "Nepal": 29187037,
            "The Netherlands": 17032845,
            "New Caledonia": 269736,
            "New Zealand": 4604728,
            "Nicaragua": 6218074,
            "Niger": 21566244,
            "Nigeria": 191836080,
            "Norway": 5330953,
            "Oman": 4742430,
            "Pakistan": 196742635,
            "Panama": 4051161,
            "Papua New Guinea": 7931944,
            "Paraguay": 6814572,
            "Peru": 32165490,
            "Philippines": 103796779,
            "Poland": 38558810,
            "Polynesia": 694694,
            "Portugal": 10264119,
            "Puerto Rico": 3679243,
            "Qatar": 2337753,
            "Reunion": 873469,
            "RB-de-Venezuela": 31922900,
            "Rep of Korea": 50708830,
            "Rep of Yemen": 28119393,
            "Romania": 19241388,
            "Russian Federation": 143374840,
            "Rwanda": 12160488,
            "St-Lucia": 187785,
            "St-Vincent and the Grenadines": 109892,
            "Samoa": 195722,
            "Sao Tome and Principe": 198506,
            "Saudi Arabia": 32743834,
            "Senegal": 16051828,
            "Serbia": 8780617,
            "Seychelles": 97569,
            "Sierra Leone": 6733695,
            "Singapore": 5784568,
            "Slovak Republic": 5432166,
            "Slovenia": 2070781,
            "Solomon Islands": 605768,
            "Somalia": 11391868,
            "South Africa": 55439484,
            "South America": 426546500,
            "South Sudan": 13095939,
            "Spain": 46071520,
            "Sri Lanka": 20903026,
            "West Bank and Gaza": 4928791,
            "Sub-Saharan Africa": 1014320080,
            "Sudan": 42165588,
            "Suriname": 552119,
            "Swaziland": 1320338,
            "Sweden": 9923520,
            "Switzerland": 8455673,
            "Syrian Arab Rep": 18908722,
            "Tajikistan": 8857317,
            "Tanzania": 56881003,
            "Thailand": 68296570,
            "Timor-Leste": 1237028,
            "Togo": 7692048,
            "Tonga": 107810,
            "Trinidad and Tobago": 1369361,
            "Tunisia": 11494296,
            "Turkey": 80417483,
            "Turkmenistan": 5501848,
            "Uganda": 41655264,
            "Ukraine": 44407470,
            "United Arab Emirates": 9397953,
            "United Kingdom": 65510800,
            "United States": 326475000,
            "US Virgin Islands": 106541,
            "Uruguay": 3456614,
            "Uzbekistan": 30689208,
            "Vanuatu": 276285,
            "Vietnam": 95413500,
            "Western Sahara": 595806,
            "Zambia": 17236366,
            "Zimbabwe": 16339318
        }
    }

    getCountries() {
        // let options = {
        //     uri: this.base_url + "countries",
        //     json: true
        // }
        // return rp(options)
        return new Promise((resolve, reject) => {
            resolve(this.countries)
        })
    }

    zombieStatusAllCountres() {
        return this.getCountries()
            .then( (countries) => {
                let countries_to_return = countries.map( (country) => {
                    let value = Math.floor(Math.random() * 10)
                    return {
                        name: country,
                        status: value
                    }
                })
                return new Promise((resolve, reject) => {
                    resolve(countries_to_return)
                })
            })
    }

    zombieStatusAllCountresSync() {
        
        let countries_to_return = this.countries.map((country) => {
            let value = Math.floor(Math.random() * 10)
            return {
                name: country,
                status: value
            }
        })
        return countries_to_return
    }

    population(country) {
        let url = this.base_url + "population/2017/" + country
        // // console.log(url)
        // let options = {
        //     url: url,
        //     json: true
        // }
        // return rp(options)
        //     .then( (data) => {
        //         let total = 0
        //         data.map((group) => {
        //             total = total + group.total
        //         })
        //         return total
        //       return new Promise((resolve, reject) => {
        //           resolve(total)
        //       })
        //     })
        // let res = request("GET", url)
        // let data = JSON.parse(res.getBody())
        // let total = 0
        // data.map(group => {
        //     total = total + group.total
        // })
        // return total
        return this.populations[country]
    }

    countriesWithPopulation() {
        return this.getCountries()
            .then( (countries) => {
                let countries_with_population = countries.map((country) => {
                    return {
                        name: country,
                        population: this.population(country)
                    }
                })
                return new Promise((resolve, reject) => {
                    resolve(countries_with_population)
                })
            })
    }
}